services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - chrome-data:/app/chrome-user-data
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - sitecraft-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3005
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - sitecraft-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sitecraft-network:
    driver: bridge

volumes:
  chrome-data:
    driver: local