version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3005:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - chrome-data:/app/chrome-user-data
    environment:
      - APP_ENV=${APP_ENV:-development}
      - PORT=3001
      # Unified environment variables are loaded via env_file
      # The backend/config/environment.js will handle the selection
    networks:
      - streetwiseweb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - APP_ENV=${APP_ENV:-development}
      - CHOKIDAR_USEPOLLING=true
      # React environment variables set by build process
      - REACT_APP_API_URL=${DEV_API_URL:-http://localhost:3005}
      - REACT_APP_SUPABASE_URL=${DEV_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${DEV_SUPABASE_ANON_KEY}
      - REACT_APP_ENV=${APP_ENV:-development}
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_DEBUG=true
    depends_on:
      - backend
    networks:
      - streetwiseweb-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  streetwiseweb-network:
    driver: bridge

volumes:
  chrome-data:
    driver: local